const CONSTANTS = {
  REGISTRY: 'REGISTRY',
  LOGIN: 'LOGIN',
  SIGNOUT: 'SINGOUT',
  SET_SESSION: 'SET_SESSION',
  LOGOUT: 'LOGOUT',
  USER_LOCATION: 'USER_LOCATION',
  ROUTE_COORDS: 'ROUTE_COORDS',
  WIPE_ROUTE: 'WIPE_ROUTE',
  SET_EXPANDED_DRAWER: 'SET_EXPANDED_DRAWER',
  CHANGE_INDUCTION: 'CHANGE_INDUCTION'
};
export default CONSTANTS;
