const CONSTANTS = {
  REGISTRY: 'REGISTRY',
  LOGIN: 'LOGIN',
  SIGNOUT: 'SINGOUT',
  SET_SESSION: 'SET_SESSION',
  LOGOUT: 'LOGOUT',
  USER_LOCATION: 'USER_LOCATION',
  ROUTE_COORDS: 'ROUTE_COORDS',
  WIPE_ROUTE: 'WIPE_ROUTE',
  SET_EXPANDED_DRAWER: 'SET_EXPANDED_DRAWER',
// ---------  Selection Interest -------------
  CHANGE_INDUCTION: 'CHANGE_INDUCTION',
  GET_DATA_INTEREST: 'GET_DATA_INTEREST',
  SHOW_DATA_INTEREST: 'SHOW_DATA_INTEREST'
};
export default CONSTANTS;
