const CONSTANTS = {
  REGISTRY: 'REGISTRY',
  LOGIN: 'LOGIN',
  SET_SESSION: 'SET_SESSION',
  LOGOUT: 'LOGOUT',
  USER_LOCATION: 'USER_LOCATION',
  ROUTE_COORDS: 'ROUTE_COORDS',
  WIPE_ROUTE: 'WIPE_ROUTE'
};
export default CONSTANTS;
